"""empty message

Revision ID: 07eef8a9e270
Revises: 3f8c93dee663
Create Date: 2022-10-17 11:15:56.358654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eef8a9e270'
down_revision = '3f8c93dee663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
